name: truck_parts_manager
description: "A new Flutter project for managing truck parts."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  pdf: ^3.10.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true